{
 "title": "Example Dashboard Learning@Cisco",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Clients Connected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(broker_clients_connected{job=\"connected_city\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine #2 Vibration Sensor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "engine-health",
     "query": "SELECT mean(\"vibration\") FROM \"engine-health\" WHERE (\"measure\" = 'engine1') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "vibration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "measure", "operator": "=", "value": "engine2" }
     ]
    }
   ]
  },
  {
   "title": "Engine #1 Vibration Sensor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "engine-health",
     "query": "SELECT mean(\"vibration\") FROM \"engine-health\" WHERE (\"measure\" = 'engine1') AND $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "vibration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "measure", "operator": "=", "value": "engine1" }
     ]
    }
   ]
  },
  {
   "title": "Broker Memory Heap",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(broker_heap_current{job=\"connected_city\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}