global:
  scrape_interval: 5s
  external_labels:
    monitor: ciscolive

scrape_configs:
  - job_name: connected_city
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:8080']
      
  - job_name: grafana
    honor_labels: true
    static_configs:
      - targets: ['grafana:3000']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
